# https://taskfile.dev

version: '3'

vars:
  BIN_NAME: server
  DIST_DIR: dist
  # 默认平台
  DEFAULT_GOOS: linux
  DEFAULT_GOARCH: amd64

tasks:
  dev:vm:
    desc: start in vm
    cmds:
      - vagrant up --provider={{.PROVIDER}}

  build:
    desc: 构建当前平台（默认启用 CGO）
    cmds:
      - go build -o {{.DIST_DIR}}/{{.BIN_NAME}} .

  check:
    cmds:
      - go tool staticcheck ./...

  lint:
    cmds:
      - go tool golangci-lint run