# https://taskfile.dev

version: '3'

vars:
  SERVER_BINARY_NAME: server
  PACK_BINARY_NAME: pack
  DIST_DIR: dist
  # 默认平台
  DEFAULT_GOOS: linux
  DEFAULT_GOARCH: amd64

tasks:
  dev:vm:
    desc: start in vm
    cmds:
      - vagrant up --provider={{.PROVIDER}}

  build:server:
    desc: 构建当前平台（默认启用 CGO）
    cmds:
      - go build -o {{.DIST_DIR}}/{{.SERVER_BINARY_NAME}} ./cmd/server

  build:pack:
    desc: 构建当前平台（默认启用 CGO）
    cmds:
      - go build -o {{.DIST_DIR}}/{{.PACK_BINARY_NAME}} ./cmd/pack


  check:
    cmds:
      - go tool staticcheck ./...

  lint:
    cmds:
      - go tool golangci-lint run