# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  serve:
    cmds:
      - go tool hugo server --buildDrafts --disableFastRender
